#! /usr/bin/env sh

set -eou

WASI_SYSROOT=/opt/wasix-sysroot make TARGET=generic ARCH=wasi USE_OBSOLETE_LINKER=yes -j14

wasm-opt -O3 --asyncify -g --fpcast-emu haproxy -o haproxy.wasm -pa max-func-params@32

rm haproxy